// Invoice i18n -- all labels used in invoice PDF rendering
// Special characters are encoded as \uXXXX escape sequences so this file
// stays pure ASCII and survives the Windows OneDrive filesystem mount.

export type InvoiceLanguage = 'en' | 'fr' | 'es'

export interface InvoiceTranslations {
  invoice: string
  invoiceNumber: string
  issueDate: string
  dueDate: string
  issued: string
  due: string
  billTo: string
  billFrom: string
  description: string
  qty: string
  rate: string
  amount: string
  subtotal: string
  discount: string
  tax: string
  creditApplied: string
  total: string
  totalDue: string
  noItems: string
  generatedBy: string
  notes: string
  paymentDetails: string
  bankTransfer: string
  mobileMoney: string
  accountName: string
  accountNumber: string
  bankName: string
  sortCode: string
  sortCodeRouting: string
  iban: string
  swift: string
  swiftIban: string
  phoneNumber: string
  phoneAccount: string
  provider: string
  status: {
    draft: string
    sent: string
    paid: string
    pending: string
    partial: string
    overdue: string
    cancelled: string
  }
  dateLocale: string
}

const translations: Record<InvoiceLanguage, InvoiceTranslations> = {
  en: {
    invoice: 'Invoice',
    invoiceNumber: 'Invoice No.',
    issueDate: 'Issue Date',
    dueDate: 'Due Date',
    issued: 'Issued',
    due: 'Due',
    billTo: 'Bill To',
    billFrom: 'Bill From',
    description: 'Description',
    qty: 'Qty',
    rate: 'Rate',
    amount: 'Amount',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    creditApplied: 'Credit applied',
    total: 'Total',
    totalDue: 'Total Due',
    noItems: 'No line items added',
    generatedBy: 'Generated by BillByDab',
    notes: 'Notes',
    paymentDetails: 'Payment Details',
    bankTransfer: 'Bank Transfer',
    mobileMoney: 'Mobile Money',
    accountName: 'Account Name',
    accountNumber: 'Account Number',
    bankName: 'Bank Name',
    sortCode: 'Sort Code',
    sortCodeRouting: 'Sort Code / Routing',
    iban: 'IBAN',
    swift: 'SWIFT / BIC',
    swiftIban: 'SWIFT / IBAN',
    phoneNumber: 'Phone Number',
    phoneAccount: 'Phone / Account',
    provider: 'Provider',
    status: {
      draft: 'Draft',
      sent: 'Sent',
      paid: 'Paid',
      pending: 'Pending',
      partial: 'Partial',
      overdue: 'Overdue',
      cancelled: 'Cancelled',
    },
    dateLocale: 'en-GB',
  },
  fr: {
    invoice: 'Facture',
    invoiceNumber: 'Facture n\u00b0',
    issueDate: 'Date d\u2019\u00e9mission',
    dueDate: '\u00c9ch\u00e9ance',
    issued: '\u00c9mis',
    due: '\u00c9ch\u00e9ance',
    billTo: 'Facturer \u00e0',
    billFrom: 'De la part de',
    description: 'Description',
    qty: 'Qt\u00e9',
    rate: 'Tarif',
    amount: 'Montant',
    subtotal: 'Sous-total',
    discount: 'Remise',
    tax: 'Taxe',
    creditApplied: 'Cr\u00e9dit appliqu\u00e9',
    total: 'Total',
    totalDue: 'Total \u00e0 payer',
    noItems: 'Aucun article ajout\u00e9',
    generatedBy: 'G\u00e9n\u00e9r\u00e9 par BillByDab',
    notes: 'Notes',
    paymentDetails: 'Coordonn\u00e9es bancaires',
    bankTransfer: 'Virement bancaire',
    mobileMoney: 'Mobile Money',
    accountName: 'Nom du compte',
    accountNumber: 'Num\u00e9ro de compte',
    bankName: 'Nom de la banque',
    sortCode: 'Code de tri',
    sortCodeRouting: 'Code de tri / Routage',
    iban: 'IBAN',
    swift: 'SWIFT / BIC',
    swiftIban: 'SWIFT / IBAN',
    phoneNumber: 'Num\u00e9ro de t\u00e9l\u00e9phone',
    phoneAccount: 'T\u00e9l. / Compte',
    provider: 'Op\u00e9rateur',
    status: {
      draft: 'Brouillon',
      sent: 'Envoy\u00e9e',
      paid: 'Pay\u00e9e',
      pending: 'En attente',
      partial: 'Partiel',
      overdue: 'En retard',
      cancelled: 'Annul\u00e9e',
    },
    dateLocale: 'fr-FR',
  },
  es: {
    invoice: 'Factura',
    invoiceNumber: 'Factura N.\u00ba',
    issueDate: 'Fecha de emisi\u00f3n',
    dueDate: 'Fecha de vencimiento',
    issued: 'Emitida',
    due: 'Vence',
    billTo: 'Facturar a',
    billFrom: 'De parte de',
    description: 'Descripci\u00f3n',
    qty: 'Cant.',
    rate: 'Tarifa',
    amount: 'Importe',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    tax: 'Impuesto',
    creditApplied: 'Cr\u00e9dito aplicado',
    total: 'Total',
    totalDue: 'Total a pagar',
    noItems: 'Sin art\u00edculos',
    generatedBy: 'Generado por BillByDab',
    notes: 'Notas',
    paymentDetails: 'Datos de pago',
    bankTransfer: 'Transferencia bancaria',
    mobileMoney: 'Dinero m\u00f3vil',
    accountName: 'Nombre de cuenta',
    accountNumber: 'N\u00famero de cuenta',
    bankName: 'Nombre del banco',
    sortCode: 'C\u00f3digo de clasificaci\u00f3n',
    sortCodeRouting: 'C\u00f3digo / Ruta',
    iban: 'IBAN',
    swift: 'SWIFT / BIC',
    swiftIban: 'SWIFT / IBAN',
    phoneNumber: 'N\u00famero de tel\u00e9fono',
    phoneAccount: 'Tel. / Cuenta',
    provider: 'Proveedor',
    status: {
      draft: 'Borrador',
      sent: 'Enviada',
      paid: 'Pagada',
      pending: 'Pendiente',
      partial: 'Parcial',
      overdue: 'Vencida',
      cancelled: 'Cancelada',
    },
    dateLocale: 'es-ES',
  },
}

export function getInvoiceTranslations(language?: string): InvoiceTranslations {
  const key = language as InvoiceLanguage
  return translations[key] ?? translations['en']
}

export const LANGUAGE_OPTIONS: { value: InvoiceLanguage; label: string; flag: string }[] = [
  { value: 'en', label: 'English', flag: '\u{1f1ec}\u{1f1e7}' },
  { value: 'fr', label: 'Fran\u00e7ais', flag: '\u{1f1eb}\u{1f1f7}' },
  { value: 'es', label: 'Espa\u00f1ol', flag: '\u{1f1ea}\u{1f1f8}' },
]
