export type InvoiceLanguage = 'en' | 'fr' | 'es'

export interface InvoiceTranslations {
  invoice: string
  invoiceNumber: string
  issued: string
  due: string
  billTo: string
  description: string
  qty: string
  rate: string
  amount: string
  subtotal: string
  discount: string
  tax: string
  total: string
  totalDue: string
  notes: string
  paymentDetails: string
  bankTransfer: string
  accountName: string
  bankName: string
  accountNumber: string
  sortCodeRouting: string
  swiftIban: string
  mobileMoney: string
  provider: string
  phoneAccount: string
  noItems: string
  generatedBy: string
  status: {
    draft: string
    sent: string
    paid: string
    pending: string
    partial: string
  }
}

const translations: Record<InvoiceLanguage, InvoiceTranslations> = {
  en: {
    invoice: 'Invoice',
    invoiceNumber: 'Invoice #',
    issued: 'Issued',
    due: 'Due',
    billTo: 'Bill To',
    description: 'Description',
    qty: 'Qty',
    rate: 'Rate',
    amount: 'Amount',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    totalDue: 'Total Due',
    notes: 'Notes',
    paymentDetails: 'Payment Details',
    bankTransfer: 'Bank Transfer',
    accountName: 'Account Name',
    bankName: 'Bank Name',
    accountNumber: 'Account Number',
    sortCodeRouting: 'Sort Code / Routing',
    swiftIban: 'SWIFT / IBAN',
    mobileMoney: 'Mobile Money',
    provider: 'Provider',
    phoneAccount: 'Phone / Account',
    noItems: 'No items added',
    generatedBy: 'Generated by BillByDab',
    status: {
      draft: 'draft',
      sent: 'sent',
      paid: 'paid',
      pending: 'pending',
      partial: 'partial',
    },
  },
  fr: {
    invoice: 'Facture',
    invoiceNumber: 'Facture n°',
    issued: 'Émis le',
    due: 'Échéance',
    billTo: 'Facturer à',
    description: 'Description',
    qty: 'Qté',
    rate: 'Tarif',
    amount: 'Montant',
    subtotal: 'Sous-total',
    discount: 'Remise',
    tax: 'Taxe',
    total: 'Total',
    totalDue: 'Total dû',
    notes: 'Notes',
    paymentDetails: 'Coordonnées de paiement',
    bankTransfer: 'Virement bancaire',
    accountName: 'Titulaire du compte',
    bankName: 'Nom de la banque',
    accountNumber: 'Numéro de compte',
    sortCodeRouting: 'Code de tri / Routage',
    swiftIban: 'SWIFT / IBAN',
    mobileMoney: 'Mobile Money',
    provider: 'Opérateur',
    phoneAccount: 'Téléphone / Compte',
    noItems: 'Aucun article ajouté',
    generatedBy: 'Généré par BillByDab',
    status: {
      draft: 'brouillon',
      sent: 'envoyée',
      paid: 'payée',
      pending: 'en attente',
      partial: 'partiel',
    },
  },
  es: {
    invoice: 'Factura',
    invoiceNumber: 'Factura n.°',
    issued: 'Emitido',
    due: 'Vence',
    billTo: 'Facturar a',
    description: 'Descripción',
    qty: 'Cant.',
    rate: 'Precio',
    amount: 'Importe',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    tax: 'Impuesto',
    total: 'Total',
    totalDue: 'Total a pagar',
    notes: 'Notas',
    paymentDetails: 'Datos de pago',
    bankTransfer: 'Transferencia bancaria',
    accountName: 'Nombre del titular',
    bankName: 'Nombre del banco',
    accountNumber: 'Número de cuenta',
    sortCodeRouting: 'Código de clasificación',
    swiftIban: 'SWIFT / IBAN',
    mobileMoney: 'Dinero móvil',
    provider: 'Proveedor',
    phoneAccount: 'Teléfono / Cuenta',
    noItems: 'Sin artículos',
    generatedBy: 'Generado por BillByDab',
    status: {
      draft: 'borrador',
      sent: 'enviada',
      paid: 'pagada',
      pending: 'pendiente',
      partial: 'parcial',
    },
  },
}

export function getInvoiceTranslations(language?: InvoiceLanguage): InvoiceTranslations {
  return translations[language ?? 'en']
}

export const LANGUAGE_OPTIONS: { value: InvoiceLanguage; label: string; flag: string }[] = [
  { value: 'en', label: 'English', flag: '🇬🇧' },
  { value: 'fr', label: 'Français', flag: '🇫🇷' },
  { value: 'es', label: 'Español', flag: '🇪🇸' },
]
